name: Blockend Checks

on:
  push:
    branches:
      - main
    paths:
      - 'blockend/**'
      - '.github/workflows/blockend.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'blockend/**'
      - '.github/workflows/blockend.yml'

  workflow_dispatch:
    inputs:
      privateKey:
        description: 'Private key for the EVM address (deploying on Goerli)'
        type: string
        required: true
      goerliUrl:
        desctiption: 'E.g. Alchemy Goerli URL with API_KEY in it'
        type: string
        required: true

jobs:
  check:
    name: Set up checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blockend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
    
  deploy:
    needs: check
    if: github.event_name == 'workflow_dispatch'
    name: Deploy the contract on Goerli
    runs-on: ubuntu-latest
    environment: staging
    defaults:
      run:
        working-directory: ./blockend
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Deploy the contract
        run: npm run deploy --network goerli
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets[github.event.inputs.privateKey] }}
          GOERLI_URL: ${{ secrets[github.event.inputs.goerliUrl] }}
