name: Update

on:
  push:
    branches:
      - main
    paths:
      - 'blockend/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'blockend/**'
      - '.github/workflows/**'

env: 
  ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTIONS_RUNTIME_URL: ${{ env.ACTIONS_RUNTIME_URL }}

jobs:
  blockend:
    name: Blockend deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./blockend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
      
      - name: Deploy the contract
        run: npm run deploy
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          GOERLI_URL: ${{ secrets.GOERLI_URL }}
      
      - name: Save artifacts
        run: npm run artifact:upload
      
      - name: Download the artifact
        run: npm run artifact:download
      
      - name: Print the artifact
        shell: bash
        run: |
          value=`cat artifacts/github/testArtifact/contractAddress.txt`
          echo The result is $value
